os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - vault status
          - name: admin/ns1/new_kv
script:
  - python hello_world.py
      
