jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: $VAULT_TOKEN
        secrets:
#           - namespace:
#             - name: ns1
#             - language_used/compiler
          - ns1/language_used
          - ns1/language_used/compiler
#           - ns2/project_id/secret_key_b
      script:
        - echo $LANGUAGE_USED
        - echo $COMPILER
#         - python --version
#         - python hello_world.py
#         - $SECRET_KEY_B
