os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - name: admin
          - ns1/new_kv/cred/token1
script:
  - python hello_world.py
  - 'ankit' == $token1
