os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - name: ns1
          - admin/ns1/new_kv
# env:
#   - NS1=$ns1
script:
  - python hello_world.py
  - echo NS1
