jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: "PfZXfN1RQ/jLKBdB4X/2iJA/pjwTcBzDK+P/8+sdrKss2Eac12r7KshVo+e5b55OZpyKKKQe64PE/3C4UAE0vh92zTnL/7RVxKDCqgvv8GVGuSqWxaxp7zsqRjj02jsa8Gfw1YnOTAsPEWUqemQlMnyP7hoLTiYBnhyY6hSwyCwYKTvrIRQLhh2FPn+pD4USa13d4/h6Z15UBLRYEMJZL1ZvttYaQ4NyJ3evcKfdNJZSHY58sm92E/gbeWHUVAV/m8cRF87804qvXW5fD2/2C7tyxJGIPvWpVsrNt1J5Ok3PaO6DWBVN2koLt6aQLnYnycKyEtJHDoOKTOEKwr43i5E4D46RO0NXqHLNS6c2HGS0RrzTqcoyNpgFcPEvI5InPKQz19bv7w4FRSkiCuVHeO0HtlDtJqJxuPIgOwNCKPCOAZticncv2xRu1B5fAnO1GMdLSB91cnwOhDaitEW/V54TENzTscEPTOhjwJfLLnvRfXZTJHy8kldiAf+3PhcSTF4DGRY8BzAA4eA5MfEJXGOmaNRZBuJvlfYaVvgLOevDcRHjxCqpebRpQ/yORathMOBsuoMVaiAuRk30K5aOKVlAjpEni3XwkwQLNisOl5DydiANvM/wUzkPJReZOm8VlCFsiju+oj08zcdy+S1hNZvu9BlDCWwmpTIVcxJiFHQ="
        secrets:
          - kv_api_ver: kv2
#           - namespace:
#             - name: ns1
#             - language_used/compiler
          - ns1/language_used
          - ns1/language_used/compiler
#           - ns2/project_id/secret_key_b
      script:
        - echo $LANGUAGE_USED
        - echo $COMPILER
#         - python --version
#         - python hello_world.py
#         - $SECRET_KEY_B
