jobs:
  include:
    - os: linux
      dist: focal
      language: python
      vault:
        api_url: https://vault-dwztla.travis-ci.com
        token: 
          secure: "Kd6G/LtshVYca8OmHEJHhae4hOPavdcr6unhahBYsYizC3ilxQDqLxq1vHmA70gSvNtSC3LPUPafFoi/KvH24/x4Kix4kxqcW9lECCJiTHaWV8/rptDYwMaJajPKjJNn7erpnAL2ICBXZ6gYhI/MP9C98m17fJAGGwN4ClyWL85XOYW45KCYHxLXn5FBJBoi3SY+po/GjlXpW0Jre4FjfD+ekLynaOpbbmFKLPCOp5UrLL6GJRDWbY8DyIWh97VdZrXfcIqpcNo1ZuvpqeTUBDQZGXH5zCbJmyPQO6Vs1lRWuTqYnCMMIjZ/7S2+dQlJO8xKUMTqUw5l3JabF6qNdeuYYRsOTON8RtcqlG92ztLFkc0Ptz6jY1Za7BPGWu7wfRT4cEFOEPZW5Ppew7naYN0kR08oJHphhJJ6Dj8DXQ2+uKZoFH54zlMdNDeFFi1Fy0s7NhMkvVxpf5B8M/k21LyJAQlJAcmRGWV+22jvxIvJ39kKxVe98Tl42+GDxrgTAVoHUaEQYxTVNAhn2ufsZsgzMvKH+FL3AXa60MMH30x2woaWoxi6nhReq8bZ4TrKeYqiY5OxyTFcjOTELtvTW5YT+AU38TLz0BZGS6kPPGGnJkx64t0EFhPWXUrxGKtwpzeRl7ltICGbrhkDy99S6WUgWIMsKrb0SNIPrv0nt9g="
        secrets:
          - kv_api_ver: kv2
#           - namespace:
#             - name: ns1
#             - language_used/compiler
          - ns1/language_used
          - ns1/language_used/compiler
#           - ns2/project_id/secret_key_b
      script:
        - echo $LANGUAGE_USED
        - echo $COMPILER
#         - python --version
#         - python hello_world.py
#         - $SECRET_KEY_B
