os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - name: ns1
          - admin/ns1/new_kv
          - name: compiler
          - admin/ns1/lang/py
env:
  - NS1=$NS1
script:
  - $compiler
  - python hello_world.py
  - NS1
