os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - vault status
          - name: ns1
script:
  - python hello_world.py
#   - vault status
#       script:
#   #       - python hello_world.py
#         - vault status
  #       - vault kv put -mount=secret creds passcode="Ankit@1234_HashiCheck"
  #       - vault kv get -mount=secret creds
      
