os: linux
dist: focal
language: python
jobs.include:
  - vault:
      api_url: $VAULT_ADDR
      token:
        secure: $VAULT_TOKEN
      secrets:
        - kv_api_ver: kv2
        - namespace:
          - name: ns1
          - admin/ns1/
          - name: compiler
          - admin/python/
env:
  - $ns1
before_script:
  - NS1= $compiler
script:
  - $compiler
  - python hello_world.py
  - echo NS1
